import type { FoodScanResult, FoodSearchResult, FoodTodayResponse } from './api';
import type { MealPlanEntry, QueuedMealPlanLog } from './mealPlanQueue';
import type { OptimisticFoodEntry } from './optimisticFoodLog';
import type { OffProduct } from './openFoodFacts';
import type { ScanHistoryEntry } from './scanHistory';
import type { SavedRecipe } from '../components/LogRecipesTabPanel';
import type { SwipeDirection } from '../components/ui/SwipeStack';
import type { LogTab } from './logSectionShared';

export interface LogTabPanelsProps {
  tab: LogTab;
  serverOnline: boolean;
  loading: boolean;
  scrollToMealPlanQueue?: number;
  scanPreviewUrl: string | null;
  scanResult: FoodScanResult | null;
  scanHistory: ScanHistoryEntry[];
  editName: string;
  editQty: string;
  onCapture: (url: string) => void;
  onClearScan: () => void;
  onRestoreScan: (entry: ScanHistoryEntry) => void;
  onClearScanHistory: () => void;
  onEditOpen: () => void;
  onLogScan: (name: string, qty: number) => void;
  offProduct: OffProduct | null;
  offQuantity: string;
  description: string;
  mealType: string;
  foodName: string;
  quantity: string;
  searchResults: FoodSearchResult[];
  pending: OptimisticFoodEntry[];
  data: FoodTodayResponse | null;
  mealPlan: MealPlanEntry[];
  loggingMealKey: string | null;
  loggingMeals: boolean;
  onLogMealPlanEntry: (entry: MealPlanEntry) => void;
  onBarcodeScan: (code: string) => void;
  onOffQuantityChange: (value: string) => void;
  onLogOffProduct: () => void;
  onVoiceLog: (e: React.FormEvent) => void;
  onDescriptionChange: (value: string) => void;
  onMealTypeChange: (value: string) => void;
  onManualLog: (e: React.FormEvent) => void;
  onFoodNameChange: (value: string) => void;
  onSelectSearchResult: (name: string) => void;
  onQuantityChange: (value: string) => void;
  onRetryPending: (entry: OptimisticFoodEntry) => void;
  onDismissPending: (id: string) => void;
  onDeleteItem: (row: number) => void;
  recipeLoading: boolean;
  recipeScanning: boolean;
  recipePhoto: string | null;
  recipeScanResult: FoodScanResult | null;
  recipe: SavedRecipe | null;
  recipeSheetsConnected: boolean | null;
  recipeEditName: string;
  recipeEditQty: string;
  onRecipePhotoCapture: (url: string) => void;
  onRecipeScanSwipe: (dir: SwipeDirection) => void;
  onRecipeEditOpen: () => void;
  onRefreshRecipe: () => void;
  onLogRecipeItem: (food: string, quantityG: number) => void;
  onLogEntireRecipe: () => void;
  mealPlanQueue: QueuedMealPlanLog[];
  syncingMealPlanQueue: boolean;
  mealPlanSyncProgress: { done: number; total: number } | null;
  failedMealPlanIds: Set<string>;
  retryingMealPlanId: string | null;
  onSyncAll: () => void;
  onRetryFailed: () => void;
  onRetry: (item: QueuedMealPlanLog) => void;
  onDismissItem: (id: string) => void;
  onClearAll: () => void;
  onLogAll: () => void;
  historyDays: { date: string; calories: number; protein: number }[];
}
